// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_login_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_login_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_login_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_login_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_login_2eproto;
namespace LoginProtocol {
class C2S_LoginLoad;
struct C2S_LoginLoadDefaultTypeInternal;
extern C2S_LoginLoadDefaultTypeInternal _C2S_LoginLoad_default_instance_;
class S2C_LoginLoad;
struct S2C_LoginLoadDefaultTypeInternal;
extern S2C_LoginLoadDefaultTypeInternal _S2C_LoginLoad_default_instance_;
}  // namespace LoginProtocol
PROTOBUF_NAMESPACE_OPEN
template<> ::LoginProtocol::C2S_LoginLoad* Arena::CreateMaybeMessage<::LoginProtocol::C2S_LoginLoad>(Arena*);
template<> ::LoginProtocol::S2C_LoginLoad* Arena::CreateMaybeMessage<::LoginProtocol::S2C_LoginLoad>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace LoginProtocol {

// ===================================================================

class C2S_LoginLoad final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LoginProtocol.C2S_LoginLoad) */ {
 public:
  inline C2S_LoginLoad() : C2S_LoginLoad(nullptr) {}
  ~C2S_LoginLoad() override;
  explicit PROTOBUF_CONSTEXPR C2S_LoginLoad(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_LoginLoad(const C2S_LoginLoad& from);
  C2S_LoginLoad(C2S_LoginLoad&& from) noexcept
    : C2S_LoginLoad() {
    *this = ::std::move(from);
  }

  inline C2S_LoginLoad& operator=(const C2S_LoginLoad& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_LoginLoad& operator=(C2S_LoginLoad&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_LoginLoad& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_LoginLoad* internal_default_instance() {
    return reinterpret_cast<const C2S_LoginLoad*>(
               &_C2S_LoginLoad_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2S_LoginLoad& a, C2S_LoginLoad& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_LoginLoad* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_LoginLoad* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_LoginLoad* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_LoginLoad>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2S_LoginLoad& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2S_LoginLoad& from) {
    C2S_LoginLoad::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2S_LoginLoad* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LoginProtocol.C2S_LoginLoad";
  }
  protected:
  explicit C2S_LoginLoad(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLoginnameFieldNumber = 1,
  };
  // bytes loginname = 1;
  void clear_loginname();
  const std::string& loginname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_loginname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_loginname();
  PROTOBUF_NODISCARD std::string* release_loginname();
  void set_allocated_loginname(std::string* loginname);
  private:
  const std::string& _internal_loginname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_loginname(const std::string& value);
  std::string* _internal_mutable_loginname();
  public:

  // @@protoc_insertion_point(class_scope:LoginProtocol.C2S_LoginLoad)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr loginname_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_login_2eproto;
};
// -------------------------------------------------------------------

class S2C_LoginLoad final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LoginProtocol.S2C_LoginLoad) */ {
 public:
  inline S2C_LoginLoad() : S2C_LoginLoad(nullptr) {}
  ~S2C_LoginLoad() override;
  explicit PROTOBUF_CONSTEXPR S2C_LoginLoad(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_LoginLoad(const S2C_LoginLoad& from);
  S2C_LoginLoad(S2C_LoginLoad&& from) noexcept
    : S2C_LoginLoad() {
    *this = ::std::move(from);
  }

  inline S2C_LoginLoad& operator=(const S2C_LoginLoad& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_LoginLoad& operator=(S2C_LoginLoad&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_LoginLoad& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_LoginLoad* internal_default_instance() {
    return reinterpret_cast<const S2C_LoginLoad*>(
               &_S2C_LoginLoad_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2C_LoginLoad& a, S2C_LoginLoad& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_LoginLoad* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_LoginLoad* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_LoginLoad* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_LoginLoad>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_LoginLoad& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_LoginLoad& from) {
    S2C_LoginLoad::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_LoginLoad* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LoginProtocol.S2C_LoginLoad";
  }
  protected:
  explicit S2C_LoginLoad(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRetFieldNumber = 1,
    kRoleIdFieldNumber = 2,
  };
  // int32 ret = 1;
  void clear_ret();
  int32_t ret() const;
  void set_ret(int32_t value);
  private:
  int32_t _internal_ret() const;
  void _internal_set_ret(int32_t value);
  public:

  // int32 role_id = 2;
  void clear_role_id();
  int32_t role_id() const;
  void set_role_id(int32_t value);
  private:
  int32_t _internal_role_id() const;
  void _internal_set_role_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:LoginProtocol.S2C_LoginLoad)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t ret_;
    int32_t role_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_login_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S_LoginLoad

// bytes loginname = 1;
inline void C2S_LoginLoad::clear_loginname() {
  _impl_.loginname_.ClearToEmpty();
}
inline const std::string& C2S_LoginLoad::loginname() const {
  // @@protoc_insertion_point(field_get:LoginProtocol.C2S_LoginLoad.loginname)
  return _internal_loginname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C2S_LoginLoad::set_loginname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.loginname_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:LoginProtocol.C2S_LoginLoad.loginname)
}
inline std::string* C2S_LoginLoad::mutable_loginname() {
  std::string* _s = _internal_mutable_loginname();
  // @@protoc_insertion_point(field_mutable:LoginProtocol.C2S_LoginLoad.loginname)
  return _s;
}
inline const std::string& C2S_LoginLoad::_internal_loginname() const {
  return _impl_.loginname_.Get();
}
inline void C2S_LoginLoad::_internal_set_loginname(const std::string& value) {
  
  _impl_.loginname_.Set(value, GetArenaForAllocation());
}
inline std::string* C2S_LoginLoad::_internal_mutable_loginname() {
  
  return _impl_.loginname_.Mutable(GetArenaForAllocation());
}
inline std::string* C2S_LoginLoad::release_loginname() {
  // @@protoc_insertion_point(field_release:LoginProtocol.C2S_LoginLoad.loginname)
  return _impl_.loginname_.Release();
}
inline void C2S_LoginLoad::set_allocated_loginname(std::string* loginname) {
  if (loginname != nullptr) {
    
  } else {
    
  }
  _impl_.loginname_.SetAllocated(loginname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.loginname_.IsDefault()) {
    _impl_.loginname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:LoginProtocol.C2S_LoginLoad.loginname)
}

// -------------------------------------------------------------------

// S2C_LoginLoad

// int32 ret = 1;
inline void S2C_LoginLoad::clear_ret() {
  _impl_.ret_ = 0;
}
inline int32_t S2C_LoginLoad::_internal_ret() const {
  return _impl_.ret_;
}
inline int32_t S2C_LoginLoad::ret() const {
  // @@protoc_insertion_point(field_get:LoginProtocol.S2C_LoginLoad.ret)
  return _internal_ret();
}
inline void S2C_LoginLoad::_internal_set_ret(int32_t value) {
  
  _impl_.ret_ = value;
}
inline void S2C_LoginLoad::set_ret(int32_t value) {
  _internal_set_ret(value);
  // @@protoc_insertion_point(field_set:LoginProtocol.S2C_LoginLoad.ret)
}

// int32 role_id = 2;
inline void S2C_LoginLoad::clear_role_id() {
  _impl_.role_id_ = 0;
}
inline int32_t S2C_LoginLoad::_internal_role_id() const {
  return _impl_.role_id_;
}
inline int32_t S2C_LoginLoad::role_id() const {
  // @@protoc_insertion_point(field_get:LoginProtocol.S2C_LoginLoad.role_id)
  return _internal_role_id();
}
inline void S2C_LoginLoad::_internal_set_role_id(int32_t value) {
  
  _impl_.role_id_ = value;
}
inline void S2C_LoginLoad::set_role_id(int32_t value) {
  _internal_set_role_id(value);
  // @@protoc_insertion_point(field_set:LoginProtocol.S2C_LoginLoad.role_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace LoginProtocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_login_2eproto
