// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank_id.proto

#include "rank_id.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace RankProtocol {
}  // namespace RankProtocol
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_rank_5fid_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_rank_5fid_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_rank_5fid_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_rank_5fid_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_rank_5fid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rrank_id.proto\022\014RankProtocol*\217\001\n\002ID\022\010\n\004"
  "ZERO\020\000\022\023\n\rC2S_RANK_BASE\020\350\207\024\022\023\n\rC2S_RANK_"
  "LOAD\020\351\207\024\022\023\n\rS2C_RANK_LOAD\020\352\207\024\022\025\n\017C2S_RAN"
  "K_UPDATE\020\353\207\024\022\025\n\017S2C_RANK_UPDATE\020\354\207\024\022\022\n\014C"
  "2S_RANK_TOP\020\320\217\024b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_rank_5fid_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_rank_5fid_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_rank_5fid_2eproto_once;
static bool descriptor_table_rank_5fid_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rank_5fid_2eproto = {
  &descriptor_table_rank_5fid_2eproto_initialized, descriptor_table_protodef_rank_5fid_2eproto, "rank_id.proto", 183,
  &descriptor_table_rank_5fid_2eproto_once, descriptor_table_rank_5fid_2eproto_sccs, descriptor_table_rank_5fid_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_rank_5fid_2eproto::offsets,
  file_level_metadata_rank_5fid_2eproto, 0, file_level_enum_descriptors_rank_5fid_2eproto, file_level_service_descriptors_rank_5fid_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_rank_5fid_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_rank_5fid_2eproto), true);
namespace RankProtocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_rank_5fid_2eproto);
  return file_level_enum_descriptors_rank_5fid_2eproto[0];
}
bool ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 328680:
    case 328681:
    case 328682:
    case 328683:
    case 328684:
    case 329680:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace RankProtocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
